"""empty message

Revision ID: 13ce020a873
Revises: 23898e1ae45
Create Date: 2015-03-08 13:47:19.987445

"""

# revision identifiers, used by Alembic.
revision = '13ce020a873'
down_revision = '23898e1ae45'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
