"""empty message

Revision ID: 23898e1ae45
Revises: 33d1e97af21
Create Date: 2015-03-08 13:29:50.018959

"""

# revision identifiers, used by Alembic.
revision = '23898e1ae45'
down_revision = '33d1e97af21'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('assignee', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'user', ['assignee'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'assignee')
    ### end Alembic commands ###
