"""empty message

Revision ID: 25e71c00de3
Revises: 519a5967384
Create Date: 2015-03-07 11:56:37.908410

"""

# revision identifiers, used by Alembic.
revision = '25e71c00de3'
down_revision = '519a5967384'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
