"""empty message

Revision ID: 2f76a7be844
Revises: 39e73b65a50
Create Date: 2015-03-07 13:00:41.939877

"""

# revision identifiers, used by Alembic.
revision = '2f76a7be844'
down_revision = '39e73b65a50'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
