"""empty message

Revision ID: 33d1e97af21
Revises: 32e8dc7b6a7
Create Date: 2015-03-07 18:50:48.042479

"""

# revision identifiers, used by Alembic.
revision = '33d1e97af21'
down_revision = '32e8dc7b6a7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
