"""empty message

Revision ID: 39e73b65a50
Revises: 25e71c00de3
Create Date: 2015-03-07 12:50:40.500102

"""

# revision identifiers, used by Alembic.
revision = '39e73b65a50'
down_revision = '25e71c00de3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
