"""empty message

Revision ID: 4d888d8082f
Revises: c5c3c9b8a1
Create Date: 2015-03-08 14:18:18.892392

"""

# revision identifiers, used by Alembic.
revision = '4d888d8082f'
down_revision = 'c5c3c9b8a1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
