"""empty message

Revision ID: 4f6e1bb032e
Revises: 57fead3c8e2
Create Date: 2015-03-07 11:27:27.765581

"""

# revision identifiers, used by Alembic.
revision = '4f6e1bb032e'
down_revision = '57fead3c8e2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
