"""empty message

Revision ID: 519a5967384
Revises: 4f6e1bb032e
Create Date: 2015-03-07 11:30:21.162664

"""

# revision identifiers, used by Alembic.
revision = '519a5967384'
down_revision = '4f6e1bb032e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
