"""empty message

Revision ID: 57fead3c8e2
Revises: 5388a859c88
Create Date: 2015-03-07 11:17:10.256718

"""

# revision identifiers, used by Alembic.
revision = '57fead3c8e2'
down_revision = '5388a859c88'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
