"""empty message

Revision ID: 5f1e2c4a22
Revises: 13ce020a873
Create Date: 2015-03-08 13:49:18.706926

"""

# revision identifiers, used by Alembic.
revision = '5f1e2c4a22'
down_revision = '13ce020a873'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
