"""empty message

Revision ID: c5c3c9b8a1
Revises: 5f1e2c4a22
Create Date: 2015-03-08 13:54:51.936809

"""

# revision identifiers, used by Alembic.
revision = 'c5c3c9b8a1'
down_revision = '5f1e2c4a22'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
